# https://github.com/dependabot/dependabot-core/issues/2521
version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0 # in case you don't want to enable version updates
    allow:
      - dependency-type: "production"
    reviewers:
      - username